# Generated by Django 5.1.3 on 2024-12-11 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Input first name', max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(help_text='Input last name', max_length=100, verbose_name='last name')),
                ('date_of_birth', models.DateField(blank=True, help_text='Input date of birth', null=True, verbose_name='date of birth')),
                ('about', models.TextField(help_text='Input about author', verbose_name='about')),
                ('photo', models.ImageField(help_text='Input author photo', upload_to='Author/%Y/%m/%d', verbose_name='photo')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Input genre book', max_length=200, verbose_name='Book name')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Input language book', max_length=200, verbose_name='Book language')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Input publisher book', max_length=200, verbose_name='Book publisher')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Input status book', max_length=200, verbose_name='Book status')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=4)),
                ('summary', models.TextField(max_length=100)),
                ('isbn', models.CharField(max_length=13)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('photo', models.ImageField(upload_to='Book/%Y/%m/%d')),
                ('author', models.ManyToManyField(to='main.author')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.genre')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.language')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.publisher')),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_nom', models.CharField(help_text='Input inviroment number', max_length=20, null=True)),
                ('due_back', models.DateField(blank=True, help_text='Input due end status', null=True)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.book')),
                ('status', models.ForeignKey(help_text='Input status book', on_delete=django.db.models.deletion.CASCADE, to='main.status')),
            ],
            options={
                'verbose_name': 'Book instance',
                'verbose_name_plural': 'Book instances',
                'ordering': ['due_back'],
            },
        ),
    ]
